GET https://joh-n-son.herokuapp.com/


###
POST http://localhost:5000/api/users


###
POST http://localhost:5000/api/users/signin
Content-Type: application/json

{
    "email": "hello@gmail.com", 
    "password": "password"
}

###
GET http://localhost:5000/api/posts


###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQGdtYWlsLmNvbSIsImlzYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTg0MjkwNjQsImV4cCI6MTU5ODQzMjY2NH0.2tY1iSxfkubJX4oYvu7zGF5JxTqXjSKj0sdGICU81LM

{
    "title": "Post 4 ",
    "content": "hello d louis  again",
    "image": "image locations"
}

###
GET http://localhost:5000/api/posts/5f45a6d465126b2085054f64


###
PATCH  http://localhost:5000/api/posts/5f439874ac1a0bb791041ee
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvMkBnbWFpbC5jb20iLCJpc2FkbWluIjp0cnVlLCJpYXQiOjE1OTgyNjM1NDQsImV4cCI6MTU5ODI2NzE0NH0.cFc9R1DnatI39mr2thLy8smk7Ng74eBtHfszhkja9ts

{
    "title": "Update roror posts",
    "content": "Updated content",
    "image": "updated location"
}

###

DELETE http://localhost:5000/api/posts/5f439b5f45a6e465126b2085054f67e909f3c3c03e855cc5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvMkBnbWFpbC5jb20iLCJpc2FkbWluIjp0cnVlLCJpYXQiOjE1OTg0MDQyMjcsImV4cCI6MTU5ODQwNzgyN30.CNJHqJ8h56J02WDUC2wEkRfl6Ngu2JCeED3wuZKZqyY

###

POST http://localhost:5000/api/comments
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvMkBnbWFpbC5jb20iLCJpc2FkbWluIjp0cnVlLCJpYXQiOjE1OTgyNjM1NDQsImV4cCI6MTU5ODI2NzE0NH0.cFc9R1DnatI39mr2thLy8smk7Ng74eBtHfszhkja9ts


{
    "name": "johnson",
    "email": "jo@gmail.com",
    "comment": "thx this blog is awesome",
    "postId":"5f439be909f3c3c03e855cc5"
}

###

GET  http://localhost:5000/api/comments
Content-Type: application/json


###

GET  http://localhost:5000/api/comments/onpost
Content-Type: application/json

{
    "postId":"5f439be909f3c3c03e855cc5"
}

###

POST http://localhost:5000/api/mail
Content-Type: application/json

{
    "name": "johnson",
    "email": "jo@gmail.com",
    "comment": "thx this blog is owsome",
    "subject": "Need to taks"

}