swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
paths:
  /api/posts:
    get:
      description: use get request to get all the article available in DB
      responses:
        '200':
          description: successful request
        '404':
          description: Post not found
    post:
      description: post request to add an article
      responses:
        '201':
          description: successful request
        '401':
          description: Unauthorized access
      parameters:
        - name: authorization
          in: header
        - name: body
          in: body
          required: true
          type: object
          schema:
            $ref: '#/definitions/postAddItem'

          


         
  /api/posts/{id}:
    get:
      description: use get request to get specific post using id
      responses:
        '200':
          description: successful request
        '404':
          description: Post not found

    patch:
      description: Update an existing article
      responses:
        '201':
          description: successful request
        '401':
          description: Unauthorized access
        '404':
          description: Post not found
      parameters:
        - name: id
          in: path
        - name: authorization
          in: header
        - name: body
          in: body
          required: true
          type: object
    delete:
      description: Update an existing article
      responses:
        '200':
          description: post deleted
        '401':
          description: Unauthorized access
        '404':
          description: Post not found
      parameters:
        - name: id
          in: path
        - name: authorization
          in: header
        
  /api/comments:
    get:
      description: use get request to get all the comments
      responses:
        '200':
          description: successful request
        '404':
          description: no comment available

    post:
      description: Update an existing article
      responses:
        '201':
          description: successful request
        '401':
          description: Unauthorized access
        '404':
          description: Post not found
      parameters:
        - name: authorization
          in: header
        - name: body
          in: body
          required: true
          type: object
          schema:
            $ref: '#/definitions/commentItem'

  

  /api/comments/onpost:
    get:
      description: use get request to get comments on certain post
      responses:
        '200':
          description: successful request
        '404':
          description: no comment available for this post
      parameters:
        - name: body
          in: body
          required: true
          type: object

  /api/mail:
    post:
      description: use post request to send email
      responses:
        '200':
          description: successful request
        '404':
          description: no comment available for this post
      parameters:
        - name: body
          in: body
          required: true
          type: object
          schema:
            $ref: '#/definitions/mailItem'


  /api/users/signin:
    post:
      description: use post request to sign in
      responses:
        '200':
          description: successful request
        '404':
          description: incorrect email/post
      parameters:
        - name: body
          in: body
          required: true
          type: object
          schema:
            $ref: '#/definitions/userItem'
          

  /api/users:
    post:
      description: use post request to sign in
      responses:
        '400':
          description: duplicate email

        '200':
          description: successfull request
        
      
      

definitions:
  postAddItem:
    type: object
    properties:
      title: 
        type: string
      content: 
        type: string
      image: 
        type: string

  commentItem:
    type: object
    properties:
      name: 
        type: string
      email: 
        type: string
      postId: 
        type: string
      comment:
        type: string

  mailItem:
    type: object
    properties:
      name: 
        type: string
      email: 
        type: string
      subject: 
        type: string
      message:
        type: string
  
  userItem:
    type: object
    properties:
      email: 
        type: string
      password: 
        type: string
      

  

  

